More memory and performance optimizations
ScorexFoundation/sigmastate-interpreter pull request #693
Opened 2020-10-12 07:25 UTC by aslesarenko

Contains further optimizations motivated by profiling node syncronization (block verification)

2020-10-26 11:10 UTC, kushti requested changes

2020-10-26 17:33 UTC, aslesarenko commented on core/src/main/scala/scalan/primitives/Functions.scala
>      override lazy val  scheduleIds: DBuffer[Int] = {
this is override, the method in the base class has ScalaDoc

2020-10-27 08:00 UTC, aslesarenko commented on core/src/main/scala/scalan/primitives/NumericOps.scala
> +  /** Descriptor of binary `%` operation (reminder of integral division). */
Added ScalaDoc here and also for BigIntIsIntegral

2020-10-27 08:01 UTC, aslesarenko commented on core/src/main/scala/scalan/primitives/Thunks.scala
> +/** Slice in Scala cake with definitions of Thunk operations. */
updated ScalaDoc with a  reference to wikipedia

2020-10-27 09:32 UTC, aslesarenko commented on core/src/main/scala/scalan/primitives/Thunks.scala
> +  class ThunkDef[A](val root: Ref[A], _scheduleIds: => ScheduleIds)
documented all public classes and methods in this file.

2020-10-27 10:47 UTC, aslesarenko commented on sigmastate/src/main/scala/org/ergoplatform/ErgoLikeContext.scala
> +  override def toSigmaContext(isCost: Boolean, extensions: Map[Byte, AnyValue] = Map()): sigma.Context = {
added more details

2020-11-01 12:52 UTC, kushti approved these changes

2020-11-02 07:27 UTC, merged