VersionContext added
ScorexFoundation/sigmastate-interpreter pull request #705
Opened 2020-11-26 14:31 UTC by aslesarenko

2020-12-10 11:00 UTC, kushti requested changes
Found some problems with updated ErgoLikeContext:

* remove default value for "val activatedScriptVersion: Byte'
* add the new field to JSON codecs

2020-12-15 12:07 UTC, kushti requested changes

2020-12-15 12:07 UTC, kushti commented on sigmastate/src/main/scala/sigmastate/serialization/SigmaSerializer.scala
> +      versionContext = VersionContext(0),
Magic number

2020-12-15 12:07 UTC, kushti commented on sigmastate/src/main/scala/sigmastate/serialization/SigmaSerializer.scala
> +  // All usages of this method should pass a version context explicitly.
Why not to do it now?

2020-12-16 12:16 UTC, aslesarenko commented on sigmastate/src/main/scala/org/ergoplatform/JsonCodecs.scala
> +      "activatedVersion" -> ctx.activatedScriptVersion.asJson
fixed

2020-12-16 12:16 UTC, aslesarenko commented on sigmastate/src/main/scala/org/ergoplatform/JsonCodecs.scala
> +      version <- cursor.downField("activatedVersion").as[Byte]
fixed

2020-12-16 12:17 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/utils/SigmaByteReader.scala
> +  * @param versionContext                 optional version context to support soft and
parameter removed

2020-12-16 12:21 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/Values.scala
> +    @inline def headerWithVersion(version: Byte): Byte = {
added

2020-12-16 12:21 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/Values.scala
> +        h = (h | ErgoTree.SizeFlag).toByte
clarified

2020-12-16 12:22 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/interpreter/InterpreterContext.scala
> +  val MaxSupportedVersion = VersionContext(
VersionContext removed entirely

2020-12-16 12:22 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/serialization/SigmaSerializer.scala
> +      versionContext = VersionContext(0),
removed

2020-12-16 12:22 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/serialization/SigmaSerializer.scala
> +  // All usages of this method should pass a version context explicitly.
removed

2020-12-17 14:21 UTC, kushti approved these changes

2020-12-17 14:21 UTC, merged