Preparation refactoring towards v5.0
ScorexFoundation/sigmastate-interpreter pull request #720
Opened 2021-03-22 15:48 UTC by aslesarenko

In this PR:
- [x] change ReductionResult into case class

2021-05-10 15:08 UTC, kushti requested changes

2021-05-10 20:50 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/interpreter/Interpreter.scala
> +  case class ReductionResult(value: SigmaBoolean, cost: Long)
fixed

2021-05-10 23:00 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/lang/SigmaBuilder.scala
> +  /** HOTSPOT: don't beautify the code. */
done

2021-05-10 23:00 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/lang/SigmaBuilder.scala
> +  object OnlyNumeric2 extends TypeConstraint2 {
done

2021-05-12 10:48 UTC, kushti approved these changes

2021-05-12 11:16 UTC, merged