Adding fromBase16 to the frontend
ScorexFoundation/sigmastate-interpreter pull request #737
Opened 2021-09-03 20:34 UTC by thub1271

Adding fromBase16 to the frontend

2021-09-08 12:37 UTC, aslesarenko commented on sigmastate/src/test/scala/sigmastate/lang/SigmaParserTest.scala
> +    parse("""fromBase58("111")""") shouldBe Apply(FromBase16Func.symNoType, IndexedSeq(StringConstant("111")))
```suggestion
    parse("""fromBase16("111")""") shouldBe Apply(FromBase16Func.symNoType, IndexedSeq(StringConstant("111")))
```

2021-09-08 13:14 UTC, aslesarenko commented
@thub1271 looks good, please fix the test

2021-09-15 19:46 UTC, thub1271 commented
@aslesarenko I have fixed the test. Please review when you get a chance.

2021-09-17 22:56 UTC, kushti commented
@thub1271 are you on Discord ? https://discord.gg/kj7s7nb dev chats are there usually, over #development channel

2021-09-23 20:03 UTC, aslesarenko approved these changes

2021-09-23 20:04 UTC, aslesarenko requested changes
The tests need to be fixed

2022-05-09 10:16 UTC, aslesarenko commented
@jozanek please also add this function to LangSpec.md

2022-05-16 19:57 UTC, aslesarenko approved these changes

2022-05-16 19:58 UTC, merged