Graph building without AOT costing
ScorexFoundation/sigmastate-interpreter pull request #797
Opened 2022-05-09 16:09 UTC by aslesarenko

2022-11-22 09:05 UTC, kushti requested changes

2022-11-22 14:07 UTC, aslesarenko commented on sigmastate/src/main/scala/org/ergoplatform/ErgoScriptPredef.scala
>    def compileWithCosting(env: ScriptEnv, code: String, networkPrefix: NetworkPrefix)(implicit IR: IRContext): Value[SType] = {
fixed

2022-11-22 14:08 UTC, aslesarenko commented on sigmastate/src/main/scala/org/ergoplatform/ErgoScriptPredef.scala
> +    assert(res.calcTree == res.buildTree)
moved to .compile()

2022-11-22 14:21 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/eval/GraphBuilding.scala
> +  protected def buildNode[T <: SType](ctx: Ref[Context], env: CompilingEnv, node: Value[T]): Ref[T#WrappedType] = {
added

2022-11-22 14:29 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/lang/SigmaCompiler.scala
> +    val IR.Pair(calcF, costF) = IR.doCosting(env, typedExpr, true)
fixed

2022-11-22 14:32 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/eval/TreeBuilding.scala
> +        mkExtractAmount(box.asBox)
This change is to unify the case with the other cases. 
The `In` pattern is equivalent to `recurse` function.

2022-11-23 12:15 UTC, kushti approved these changes

2022-11-23 15:21 UTC, merged