[v5.0.1] remove AOT costing code
ScorexFoundation/sigmastate-interpreter pull request #801
Opened 2022-05-15 13:15 UTC by aslesarenko

2022-12-01 18:48 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/eval/GraphBuilding.scala
This is not new code, it is moved from other traits of the IR cake.

2022-12-07 13:00 UTC, kushti requested changes
Will re-check `CBigInt` and `CGroupElement` during the second round (reminder for self)

2022-12-07 14:25 UTC, aslesarenko commented on sigmastate/src/main/scala/org/ergoplatform/SigmaConstants.scala
> +  object MaxPropositionBytes extends SizeConstant[Int](4096 /*4K*/, 5,
The doc for each constant is in the description. Added ScalaDoc for SizeConstant class.

2022-12-07 14:27 UTC, aslesarenko commented on sigmastate/src/main/scala/org/ergoplatform/SigmaConstants.scala
> +  object MaxBoxSizeWithoutRefs extends SizeConstant[Int](MaxBoxSize.value - (CryptoConstants.hashLength + 2/*size of Short*/), 6,
same as above

2022-12-07 15:20 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/eval/GraphBuilding.scala
> +  object AnyOf {
fixed.

2022-12-07 15:24 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/interpreter/InterpreterContext.scala
> +  def toSigmaContext(extensions: Map[Byte, AnyValue] = Map()): sigma.Context
fixed

2022-12-19 22:43 UTC, kushti approved these changes

2022-12-20 10:10 UTC, merged