[v5.0.1] Refactor tests
ScorexFoundation/sigmastate-interpreter pull request #802
Opened 2022-05-15 15:55 UTC by aslesarenko

2022-11-23 12:42 UTC, kushti requested changes
Add ScalaDoc for `TreeBuilding` also.

`Evaluation` is not descriptive enough name I guess

Please specify in ScalaDoc comments whether classes belong to frontend compiler or tree interpreter.

2022-11-23 12:42 UTC, kushti commented on sigmastate/src/main/scala/sigmastate/eval/IRContext.scala
> +trait IRContext extends TreeBuilding with GraphBuilding {
ScalaDoc missed

2022-12-01 14:37 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/eval/IRContext.scala
> +trait IRContext extends TreeBuilding with GraphBuilding {
fixed

2022-12-01 14:47 UTC, aslesarenko commented on sigmastate/src/main/scala/sigmastate/eval/Evaluation.scala
>  object Evaluation {
fixed. Also added TODO to either rename it or find a better place for the methods after code reorganization in next PRs.

2022-12-01 14:57 UTC, aslesarenko commented
> Please specify in ScalaDoc comments whether classes belong to frontend compiler or tree interpreter.
@kushti in #827 and #833 the consensus code is moved into separate module which doesn't depend on  both compiler and graph-IR code. See `interpreter` and `sc` (aka sigma compiler) modules.

2022-12-13 14:50 UTC, kushti approved these changes

2022-12-13 14:54 UTC, merged