LangSpec.md updated + more ScalaDocs
ScorexFoundation/sigmastate-interpreter pull request #848
Opened 2022-12-08 21:34 UTC by aslesarenko

2022-12-09 18:43 UTC, kushti requested changes
What about other changes from ? https://github.com/ScorexFoundation/sigmastate-interpreter/milestone/9?closed=1 

See no changes in regards with Unit, flatmap , zip/append , xor,

2022-12-09 18:43 UTC, kushti commented on docs/LangSpec.md
> +box.R3[Int].getOrElse(d) // access R3 register, check that its value of type Int, return it if defined, otherwise return `d`
What if it is defined but not of type Int?

2022-12-13 16:38 UTC, aslesarenko commented
> What about other changes from ? https://github.com/ScorexFoundation/sigmastate-interpreter/milestone/9?closed=1 
> See no changes in regards with Unit, flatmap , zip/append , xor,

All the changes are invisible for developers, because all of them fix bugs so that after activation the operations work as expected (and documented).
E.g. `zip` used to produce invalid result for collections of different length, and `append` failed with exception in some situation.

2023-02-09 20:48 UTC, kushti commented
@aslesarenko see no .propBytes property of SigmaProp type

2023-02-10 12:47 UTC, kushti approved these changes

2023-02-10 15:04 UTC, merged