Removing unused code #1
ScorexFoundation/sigmastate-interpreter pull request #944
Opened 2023-12-18 10:56 UTC by kushti

In this PR, different unused imports, assignments, arguments are removed

2023-12-18 11:16 UTC, aslesarenko commented
@kushti, please fix the tests.

2023-12-18 23:07 UTC, kushti commented
> @kushti, please fix the tests.

fixed

2023-12-19 17:18 UTC, aslesarenko requested changes
Looks good, but needs to be merged with v5.0.14-RC, as this is the latest version.

2023-12-26 10:31 UTC, kushti commented on interpreter/shared/src/main/scala/sigmastate/serialization/ValueSerializer.scala
>        s.toString
assignment is not needed anyway, fixed with a note

2023-12-26 10:31 UTC, kushti commented
> Looks good, but needs to be merged with v5.0.14-RC, as this is the latest version.

Merging done. please make another round

2023-12-26 12:35 UTC, aslesarenko approved these changes

2023-12-26 12:46 UTC, merged