[6.0] Header.checkPow method
ScorexFoundation/sigmastate-interpreter pull request #968
Opened 2024-04-27 18:18 UTC by kushti

2024-08-01 11:01 UTC, kushti commented
JS test was failing due to #1023 , fixed now

2024-08-08 19:34 UTC, aslesarenko requested changes

2024-08-08 20:34 UTC, kushti commented on data/shared/src/main/scala/sigma/ast/values.scala
> +        }
Possible, however, there are some questions to resolve then :

* NewFeature implementation by  you was expecting this: 

```
    override def isSupportedIn(vc: VersionContext): Boolean =
      vc.activatedVersion >= sinceVersion && vc.ergoTreeVersion >= sinceVersion
```
why ?

* what does tree version mean at all ? How tree of version v+1 is different from tree version v?

2024-08-12 11:02 UTC, kushti commented on data/shared/src/main/scala/sigma/pow/Autolykos2PowValidation.scala
> +  def hitForVersion2ForMessage(k: Int, msg: Array[Byte], nonce: Array[Byte], h: Array[Byte], N: Int): BigInt = {
done

2024-08-12 11:03 UTC, kushti commented on data/shared/src/main/scala/sigma/pow/Autolykos2PowValidation.scala
> +  val group: BcDlogGroup = CryptoConstants.dlogGroup
done

2024-08-12 11:03 UTC, kushti commented on data/shared/src/main/scala/sigma/ast/values.scala
> +        }
Rollback versioning by tree and changed NewFeature definition. The question about versioning semantics still remains.

2024-08-12 11:04 UTC, kushti commented
@aslesarenko comments addressed, please make another pass

2024-08-24 09:40 UTC, aslesarenko commented on data/shared/src/main/scala/sigma/ast/values.scala
> +        }
This "vc.activatedVersion >= sinceVersion && vc.ergoTreeVersion >= sinceVersion" was an intermediate version, which was fixed in the in my original more recent PRs. 
The tree version is more about bytecode format, see for example switch from v0, to v1, there size has become required. However, there is also a relation between tree version and block version, s.t. treeVersion <= activatedScriptVersion.

2024-08-24 09:44 UTC, aslesarenko approved these changes
LGTM, also see comment about tree version.

2024-09-02 17:13 UTC, merged