[6.0] Fix SubstConstants: serialize ErgoTree size
ScorexFoundation/sigmastate-interpreter pull request #995
Opened 2024-05-22 19:54 UTC by aslesarenko

2024-06-07 10:09 UTC, kushti requested changes
This PR contains serious changes to another 6.0 method, serialize ( introducing CheckMinimalErgoTreeVersion rule). Those changes should be moved to corresponding PR.

2024-06-12 15:25 UTC, aslesarenko reviewed
LGTM, but please address comments and consider it approved (github doesn't allow approval of own PR)

2024-06-12 15:25 UTC, aslesarenko commented on sc/shared/src/test/scala/sigmastate/lang/SigmaBinderTest.scala
> -    */
Why the scaladoc is removed?

2024-08-05 17:01 UTC, kushti commented on sc/shared/src/test/scala/sigmastate/lang/SigmaBinderTest.scala
> -    */
restored

2024-08-05 17:01 UTC, kushti approved these changes

2024-08-05 17:03 UTC, merged